name: "Build and test"

on: pull_request

jobs:

  # Check for secrets leak in the repository
  secrets-scanner:
    uses: matter-labs/era-compiler-ci/.github/workflows/secrets-scanner.yaml@v1
    secrets: inherit

  # Check for cargo issues
  cargo-check:
    runs-on: ubuntu-latest
    container:
      image: matterlabs/llvm_runner:ubuntu22-llvm17-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cargo checks
        uses: matter-labs/era-compiler-ci/.github/actions/cargo-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: cargo build --verbose
