name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  # Cargo checks
  cargo-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matter-labs/zksync-llvm-runner:latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo checks
        uses: matter-labs/era-compiler-ci/.github/actions/cargo-check@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    runs-on: matterlabs-ci-runner-high-performance
    container:
      image: ghcr.io/matter-labs/zksync-llvm-runner:latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run unit tests
        uses: matter-labs/era-compiler-ci/.github/actions/rust-unit-tests@v1
        with:
          target: "x86_64-unknown-linux-gnu"
          enable-coverage: true
          coverage-token: ${{ secrets.CODECOV_TOKEN }}

  # Special job that allows some of the jobs to be skipped or failed
  # requiring others to be successful
  pr-checks:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - cargo-check
      - build-test
    steps:
      - name: Decide on PR checks
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
